export interface BillingInterface {
    BilllingId : number,
    Team : string,
    Team_CF : string,
    Sub_Team : string,
    Sub_Team_CF : string,
    Sub_Project : string,
    Emp_ID : number,
    Employee_Name : string,
    PIF_ID : string,
    Rev_Source: string,
    Cus_Div: string,
    Cus_Div_CF: string,
    DI: string,
    MCR: string,
    Onsite_Nearshore_Offshore: string,
    Cus_Country : string,
    Cus_Country_CF : string,
    Contract_Type : string,
    Rate_In_Billing: number,
    CONV: string,
    Plan_1: number,
    Billed_1: number,
    Unbilled_SAP_1: number,
    Unbilled_No_PO_1: number,
    Other_Rev_1: number,

    Plan_2: number,
    Billed_2: number,
    Unbilled_SAP_2: number,
    Unbilled_No_PO_2: number,
    Other_Rev_2: number,

    Plan_3: number,
    Billed_3: number,
    Unbilled_SAP_3: number,
    Unbilled_No_PO_3: number,
    Other_Rev_3: number,

    Plan_4: number,
    Billed_4: number,
    Unbilled_SAP_4: number,
    Unbilled_No_PO_4: number,
    Other_Rev_4: number,

    Plan_5: number,
    Billed_5: number,
    Unbilled_SAP_5: number,
    Unbilled_No_PO_5: number,
    Other_Rev_5: number,

    Plan_6: number,
    Billed_6: number,
    Unbilled_SAP_6: number,
    Unbilled_No_PO_6: number,
    Other_Rev_6: number,

    Plan_7: number,
    Billed_7: number,
    Unbilled_SAP_7: number,
    Unbilled_No_PO_7: number,
    Other_Rev_7: number,

    Plan_8: number,
    Billed_8: number,
    Unbilled_SAP_8: number,
    Unbilled_No_PO_8: number,
    Other_Rev_8: number,

    Plan_9: number,
    Billed_9: number,
    Unbilled_SAP_9: number,
    Unbilled_No_PO_9: number,
    Other_Rev_9: number,

    Plan_10: number,
    Billed_10: number,
    Unbilled_SAP_10: number,
    Unbilled_No_PO_10: number,
    Other_Rev_10: number,

    Plan_11: number,
    Billed_11: number,
    Unbilled_SAP_11: number,
    Unbilled_No_PO_11: number,
    Other_Rev_11: number,

    Plan_12: number,
    Billed_12: number,
    Unbilled_SAP_12: number,
    Unbilled_No_PO_12: number,
    Other_Rev_12: number,
}